### ISSUE TITLE
優化代碼結構

### ISSUE THREAD

**Issue by GANSOONLEE** [tooruche520/DiscordBot_TK4#13]
### 敘述
利用 `pytz` 模組來解決文件 [greetings_data.py](https://github.com/tooruche520/DiscordBot_TK4/blob/debug/src/greetings_data.py)
時間直接加8小時的辦法

### 思路
```python3
#獲取當前時間
now = datetime()
#獲取使用者的時區
user_tz = pytz.timezone("Asia/Taipei")
#將時間轉換成使用者的時區
user_time = now.astimezone(user_tz)
```

之後我還要在研究一下@@

**Comment by GANSOONLEE** [comment]
+ 嘗試使用與 UTC 時間的偏移量來加上 `time_send` 而不是直接加8小時
#14 

**注意功能需要測試**

**Comment by tooruche520** [comment]
OK
會在之後的版本中加入
